name: Java CI

on: [pull_request]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 12.0.1
      uses: actions/setup-java@v1
      with:
        java-version: 12.0.1
    - name: Build with Gradle
      run: ./gradlew build
